# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  sender_mail: '%env(EMAIL)%'
  app_name: '%env(COMPOSE_PROJECT_NAME)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\OpenApi\JwtDecorator:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\OpenApi\JwtDecorator.inner' ]
    autoconfigure: false

  App\OpenApi\RefreshTokenDecorator:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\OpenApi\RefreshTokenDecorator.inner' ]
    autoconfigure: false

  App\Serializer\PlanContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    arguments: [ '@App\Serializer\PlanContextBuilder.inner' ]
    autoconfigure: false

  App\Serializer\UserContextBuilder:
    decorates: 'api_platform.serializer.context_builder'
    arguments: [ '@App\Serializer\UserContextBuilder.inner' ]
    autoconfigure: false

  App\Serializer\Denormalizer\PlanDenormalizer:
    tags:
      - { name: serializer.normalizer }

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
